chat/urls.py
from django.urls import path, include

from .views import rm

app_name='chat'

urlpatterns=[
    path('<str:other_usr>/', rm, name='room'),
]

eg/urls.py
import django
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from entry.views import sgnup, logn
from django.conf.urls.static import static
from home.views import home

urlpatterns = [
    path('registration/',include('entry.urls')),
    path('guidee/',include('guidee.urls')),
    path('guide/',include('guide.urls')),
    path('chat/',include('chat.urls')),
    path('',home, name='home'),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

guidee/urls.py
from django.urls import path, include

from .views import gdlst, gdprofile, r_queslst

urlpatterns=[

    path('<str:field>/guidelist',gdlst, name='gdlst'),
    path('<str:field>/relatedqueslst',r_queslst, name='r_queslst'),
    path('guidecontactlist',gdlst, name="gdcontactlst"),
    path('<str:field>/<str:guide>', gdprofile, name='gdprofile'),
    
]

entry/models.py
from distutils.command.upload import upload
from email.policy import default
from operator import mod
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator



class fields(models.Model):
    no=models.IntegerField()
    name=models.CharField(max_length=200, primary_key=True)
    guides=models.ManyToManyField(User,related_name='guides',blank=True)
    guidees=models.ManyToManyField(User,related_name='guidees',blank=True)
    def __str__(self):
        return str(self.name)

def image_path(instance,filename):
    ext= filename.split('.')[-1]
    filename='{}.{}'.format(str(instance.usr.id)+str('_dp'),ext)
    return '{0}/{1}/{2}'.format(instance.usr.id,'DP',filename)


class Question(models.Model):
    ques=models.TextField()
    fd=models.ForeignKey(fields,on_delete=models.CASCADE)
    guidee=models.ForeignKey(User,related_name="guidee", on_delete=models.CASCADE)
    guide=models.ForeignKey(User, related_name="guide",on_delete=models.CASCADE)
    time_asked=models.DateTimeField(auto_now_add=True)
    status=models.IntegerField(default=0)
    ans=models.TextField(blank=True, null=True)
    class Meta:
        ordering=['-time_asked']

class Review(models.Model):
    rvw=models.TextField()
    gd=models.ForeignKey(User, related_name="rvw_guides", on_delete=models.CASCADE)
    gde=models.ForeignKey(User, related_name="rvw_guidees", on_delete=models.CASCADE)
    time_sent=models.DateTimeField(auto_now_add=True)
    status=models.CharField(max_length=15,default="gde_gd")

class Rating(models.Model):
    value=models.FloatField(validators=[MinValueValidator(0.0),MaxValueValidator(5.0)],)
    gd=models.ForeignKey(User, related_name="rating_guides", on_delete=models.CASCADE)
    gde=models.ForeignKey(User, related_name="rating_guidees", on_delete=models.CASCADE)
    status=models.CharField(max_length=15,default='gde_gd')
    time_rated=models.DateTimeField(auto_now=True)


class usrinfo(models.Model):
    usr=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    DP=models.ImageField(upload_to=image_path,blank=True)
    def __str__(self):
        return str(self.usr)

guidee/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from entry.models import fields, Question, Review, Rating
from chat.models import room



class guideeinfo(models.Model):
    usr=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    fds=models.ManyToManyField(fields,related_name='interested_fields')
    rating=models.FloatField(default=0.0)
    ratings_received=models.ManyToManyField(Rating, related_name="guidee_received", blank=True)
    ratings_given=models.ManyToManyField(Rating, related_name="guidee_rated", blank=True)
    questions_asked=models.ManyToManyField(Question,related_name="questions_asked",blank=True)
    guidee_availablemode=models.IntegerField(default=0)
    guidee_rooms=models.ManyToManyField(room, blank=True,related_name="guidee_rooms")
    rvws_received=models.ManyToManyField(Review,blank=True,related_name="reviews_received_bygde")
    rvws_posted=models.ManyToManyField(Review,blank=True, related_name="reviews_posted_bygde")

    def __str__(self):
        return str(self.usr)

guidee/forms.py
from cProfile import label
from dataclasses import fields
from pyexpat import model
from turtle import fd
from django import forms
from django.forms import ModelForm 

from .models import fields as fds
from guide.models import Certificate

from entry.models import Review
class Rvw_form(forms.Form):
    Rvw=forms.CharField(label='Your review', widget=forms.Textarea())
   

guidee/views.py
from multiprocessing.sharedctypes import Value
from telnetlib import STATUS
from turtle import fd
from unicodedata import name
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank

from entry.models import fields,usrinfo, Question, Review, Rating

from django.contrib.auth.models import User

from .forms import Rvw_form

def gdlst(request,field=None):
    if field==None:
        usr=User.objects.get(username=str(request.user))
        rms=[]
        for rm in usr.guideeinfo.guidee_rooms.all():
            if rm.status == "r":
                rms+=[rm]
        lst_type="contact_lst"
        return render(request,'guidee/ongoing_queslst.html',{'rms':rms,'usrinfo':usrinfo,'type':lst_type})
    else:        
        fd=fields.objects.get(name=field)
        print(fd)
        gds=fd.guides.all()
        print(gds)
        lst_type="fd_gd_lst"
        return render(request,'guidee/gdlst.html',{'gds':gds,'usrinfo':usrinfo,'fd':fd,'type':lst_type})

def r_queslst(request,field=None):
    fd=fields.objects.get(name=field)
    question=request.GET.get('ques')
    r_q= fd.question_set.all().annotate(rank=SearchRank(SearchVector('ques'),SearchQuery(str(question)))).order_by('-rank')
    related_ques=[]
    for q in r_q:
        if q.status==4:
            related_ques+=[q]
    return render(request,'guidee/queslst.html',{'ques':question,'fd':fd, 'related_ques':related_ques})



def gdprofile(request,field,guide):
    gd=User.objects.get(username=guide)
    fd=fields.objects.get(name=field)
    usr=User.objects.get(username=str(request.user))
    if request.method=='GET':
        if request.GET.get('ques') is not None:
            question=request.GET.get('ques')
            print(question)
            r_q= gd.guideinfo.questions_byguidees.all().annotate(rank=SearchRank(SearchVector('ques'),SearchQuery(str(question)))).order_by('-rank')
            related_ques=[]
            for q in r_q:
                if q.status==4:
                    related_ques+=[q]
            print(related_ques)
            return render(request,'guidee/gdconnect.html',{'ques':question,'gd':gd,'fd':fd, 'connect_asked':False, 'related_ques':related_ques})
        else:
            certs=gd.guideinfo.certificates.all()
            certificates=[]
            for c in certs:
                print(c.fd, fd)
                if c.fd == fd:
                    certificates+=[c]
            print(certs, gd, certificates)
            rvw_form=Rvw_form()
            return render(request,'guidee/gdprofile.html',{'gd':gd,'certificates':certificates,'connect_asked':False, 'rvw_form':rvw_form})
    elif request.method=='POST':
        print("rp")
        if request.GET.get('ques') is not None:
            question=request.GET.get('ques')
            print(question)
            if 'sending_ques' in request.POST:
                print(question)
                Q=Question(ques=question,guide=gd,guidee=usr,fd=fd)
                Q.save()
                gd.guideinfo.questions_byguidees.add(Q)
                usr.guideeinfo.questions_asked.add(Q)
                ques_sent=True
            elif 'unsending_ques' in request.POST:
                Q=Question.objects.get(ques=question,fd=fd,guidee=usr,guide=gd)
                usr.guideeinfo.questions_asked.remove(Q)
                Q.delete()
                ques_sent=False
            
            r_q= gd.guideinfo.questions_byguidees.all().annotate(rank=SearchRank(SearchVector('ques'),SearchQuery(str(question)))).order_by('-rank')
            related_ques=[]
            for q in r_q:
                if q.status==4:
                    related_ques+=[q]
            print(related_ques)
            return render(request,'guidee/gdconnect.html',{'ques':question,'gd':gd, 'fd':fd, 'ques_sent':ques_sent,'related_ques':related_ques})
        elif 'rvw_post' in request.POST:
            rvw=request.POST['rvw']
            rvw_object=Review.objects.create(rvw=rvw,gd=gd,gde=usr,status="gde_gd")
            usr.guideeinfo.rvws_posted.add(rvw_object)
            usr.guideeinfo.save()
            gd.guideinfo.rvws_received.add(rvw_object)
            gd.guideinfo.save()
            rvw_form=Rvw_form()
            certs=gd.guideinfo.certificates.all()
            certificates=[]
            for c in certs:
                print(c.fd, fd)
                if c.fd == fd:
                    certificates+=[c]
            return render(request,'guidee/gdprofile.html',{'gd':gd,'certificates':certificates,'connect_asked':False, 'rvw_form':rvw_form})
        elif 'rate' in request.POST:
            r=request.POST['rating']
            print(r)
            for rating in gd.guideinfo.ratings_received.all():
                print('rating')
                print(rating.gde == usr)
                print('rating end')
                if rating.gde == usr:
                    t='ch'
                    break
            else:
                t='add'
            gd_r_c=gd.guideinfo.ratings_received.all().count()
            if t=='ch':
                r_object=Rating.objects.get(gd=gd, gde=usr,status='gde_gd')
                print(r_object.value,float(r))
                ch_r=((-(r_object.value))+float(r))/(gd_r_c)
                print(ch_r)
                f_r=(gd.guideinfo.rating)+ch_r
                r_object.value=float(r)
                r_object.save()
            elif t=='add':
                r_s=(gd.guideinfo.rating)*(gd_r_c)
                r_s+=float(r)
                f_r=float(r_s/(gd_r_c+1))
                r_object=Rating.objects.create(value=float(r),gd=gd,gde=usr,status='gde_gd')
                usr.guideeinfo.ratings_given.add(r_object)
                usr.guideeinfo.save()
                gd.guideinfo.ratings_received.add(r_object)                
            gd.guideinfo.rating=f_r
            gd.guideinfo.save()
            rvw_form=Rvw_form()
            certs=gd.guideinfo.certificates.all()
            certificates=[]
            for c in certs:
                print(c.fd, fd)
                if c.fd == fd:
                    certificates+=[c]
            return render(request,'guidee/gdprofile.html',{'gd':gd,'certificates':certificates,'connect_asked':False, 'rvw_form':rvw_form})

            

                


            
    

            
    
            




            
            

guidee/templates/guidee/gdconnect.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'stgdconnect.css' %}">
        <title>Q&A by guide</title>
    </head>
    <body>
        <div class="top">
            <a href="{% url 'home' %}" >Home</a>
            <a href="{% url 'logout'%}">Logout</a>
        </div>
        <div class= "ques">
            <p style="text-align:left;padding-top:0%">{{ques}}</p>
        </div>
        <div>
            <hr>
        </div>
        <div class= "qac">
            <div class="qa">
                {% for q in related_ques %}
                <div class=" qai qa1">
                    <p class="q">{{q.ques}}</p>
                    <p class="a">{{q.ans}}</p>
                </div>
                {% endfor %}
                
            </div>
            <div class="cnct">
                <div class="cncti cnctm">
                    {% if gd.guideinfo.connectmode == 0 %}
                    <span>Connect mode :- Not ready to contact </span>
                    {%else%}
                    <span>Connect mode :- Ready to contact </span>
                    {%endif%}
                    <form action="" method="post">
                    {% if not ques_sent %}
                    <input type="submit" value="send question" name="sending_ques">
                    {%csrf_token%}
                    {%else%}
                    <input type="submit" value="unsend question" name="unsending_ques">
                    {%csrf_token%}
                    </form>
                    {%endif%}
                    
                </div>
                <button type="button" value="Chat" class="btn btnch" onclick=chat()>Chat</button>
                <button type="button" value="Audio Call" class="btn btnac">Audio Call</button>
                <button type="button" value="Video Call" class="btn btnvc">Video Call</button>
            </div>
            {{ gd.guideinfo.connectmode|json_script:"c_m" }}
            {{ gd.username|json_script:"gd" }}
            {{ fd.no|json_script:"fd_no" }}
            {{ ques.id|json_script:"ques_id" }}

            <script src="{%static 'jsgdconnect.js'%}"></script>
    </body>
</html>

guidee/templates/guidee/gdlst.html
{%load static%}
<Doctype! html>
    <html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{%static 'stgdlst.css'%}" type="text/css">
        <title>
            {% if  type == 'fd_gd_lst' %}
            List of Guides
            {% elif type == 'contact_lst' %}
            Guides Contacted
            {% endif %}
        </title>
    </head>

    <body>
        <div class="top">
            <a href="{% url 'home' %}" >Home</a>
            <a href="{% url 'logout'%}">Logout</a>
        </div>
        <div class="header">
            {% if  type == 'fd_gd_lst' %}    
            <h1 class="field">{{fd}} </h1>
            {% elif type == 'contact_lst' %}
            <h1 class="cnctlstheader">Guide Contact list</h1>
            {% endif %}
            <br>
            <h2 class="guides"> Guides </h2>
        </div>
        <hr>
        <div >
            <form action="" method="post" novalidate>
            <table class="list">
                <tr class="row">
                    <th class="name">Name</th>
                    <th class="level">Level</th>
                    <th class="Qual">Qualification</th>
                    <th class="rating">Rating</th>
                </tr>
                {%for gd in gds%}
                <tr>
                    {% if  type == 'fd_gd_lst' %}
                    <td class="name"><a href="../{{fd}}/{{gd}}">{{gd}}</a></td>
                    {% elif type == 'contact_lst' %}
                    <td class="name"><a href="{% url 'chat:room' other_usr=gd.username %}?requestfrom=guidee">{{gd}}</a></td>
                    {% endif %}
                    <td>{{gd.guideinfo.level}}</td>
                    <td class="Qual">B.tech IIT</td>
                    <td>{{gd.guideinfo.rating}}</td>
                </tr>
                {%endfor%}
            </table>
            {% csrf_token %}
            </form>
            <hr>
            <form>
                <label class="label">Question:-</label>
                <textarea class="question" id="ques" cols="400" rows="6" placeholder="Type your question here"></textarea>
                <input class="sbmtq" type="button" value="submit" onclick=sbmtqs() >
            </form>

        </div>
        <script src="{% static 'jsgdlst.js' %}"></script>
    </body>

    </html>

guidee/templates/guidee/gdprofile.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'stgdprofile.css'%}" type="text/css">
        <title>
            Profile of guide</title>
    </head>
    <body>
        <div class="top">
            <a href="{% url 'home' %}" >Home</a>
            <a href="{% url 'logout'%}">Logout</a>
        </div>
        <h1> {{gd}}'s Profile</h1>
        <br>
        <div class="row">
            <div class="column cert">
                {% for c in certificates %}
                <a href='{{c.certificate.url}}' target="_blank" >{{c.issuedby}}</a>
                {% endfor %}
            </div>
            <div class="column prof">
                <img src="{{gd.usrinfo.DP.url}}" ,alt="profile pic" width="200px"
                    height="100px">
                <p class="name">Name</p>
            </div>
            <div class="column perf">
                <p class="pd">
                   Level :- {{gd.guideinfo.level}}<br> Rating :- {{gd.guideinfo.rating}}
                </p>

            </div>
        </div>
        <div class="hr">
            <p></p>
            <p><hr></p>
            
        </div>
        <div class="ques">
            <form action="" method="post">
                <label for=""> Question:-</label>
                <br>
                <textarea class="in" name="question" id="id_question" rows="11" placeholder="Type your Question here"></textarea>
                <br>
                <input class="sbmt" type="button" value="submit" name="ques_submit" onclick=qagf() >
                {%csrf_token%}
            </form>
        </div>
        <div style="clear:both"><br><hr></div>
        <div class="btm">
            <div style="float: right;">  
                <form action="" method="post">
                <input type="submit" value="rate" name="rate">
                <input type="text" name="rating">
                {%csrf_token%}
                </form>
            </div>
            <div >Review:-
            </div>
            <form action="" method="post" >
            <div>
                <textarea name="rvw" cols="200" rows="3" required="" id="id_rvw" placeholder="Your Review"></textarea>
                <input type="submit" value="post" name="rvw_post" >
            </div>
            {%csrf_token%}
            </form>
            <button type="button" onclick=shrevs() >Show all reviews</button>
        </div>
        <div id="rvs">
            {% for rvw in gd.guideinfo.rvws_received.all %}
            <div class="revs revl">{{rvw.gde}}:-</div>
            <div class="revs revl"><label>{{rvw.rvw}}</label></div>
            {%endfor%}
        </div>
            
        </div>
        <Script src="{%static 'js.js' %}"></Script>
    </body>
</html>

guidee/templates/guidee/ongoing_queslst.html
{%load static%}
<Doctype! html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{%static 'stgdlst.css'%}" type="text/css">
        <title>
            Ongoing Questions
        </title>
    </head>

    <body>
        <div class="top">
            <a href="{% url 'home' %}" >Home</a>
            <a href="{% url 'logout'%}">Logout</a>
        </div>
        <div class="header">
            <h1 class="cnctlstheader">On going questions</h1>
            <br>
            <h2 class="guides"> Questions </h2>
        </div>
        <hr>
        <div>
            <form action="" method="post" novalidate>
            <table class="list">
                <tr class="row">
                    <th class="name">Guide</th>
                    <th class="level">Field</th>
                    <th class="Qual">Question</th>
                    <th class="rating">Time asked</th>
                </tr>
                {%for rm in rms%}
                <tr>                    
                    <td class="name"><a href="/chat/{{rm.guide}}?requestfrom=guidee&fd_no={{rm.fd.no}}&ques_id={{rm.ques.id}}">{{rm.guide}}</a></td>        
                    <td>{{rm.fd}}</td>
                    <td class="Qual">{{rm.ques.ques}}</td>
                    <td>{{rm.time_asked}}</td>
                </tr>
                {%endfor%}
            </table>
            {% csrf_token %}
            </form>
            <hr>

        </div>
        <script src="{% static 'jsgdlst.js' %}"></script>
    </body>

    </html>

guidee/templates/guidee/queslst.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'stqueslst.css' %}">
        <title>Q&A by guide</title>
    </head>
    <body>
        <div class= "ques">
            <p style="text-align:left;padding-top:0%">{{ques}}</p>
        </div>
        <div>
            <hr>
        </div>
        <div class= "qac">
            <div class="qa">
                {% for q in related_ques %}
                <div class="gi gi1">
                    <p class="gie gn gn1" ><button id="{{q.guide}}" onclick=pogf(this.id) >{{q.guide}}</button></p>
                    <p class="gie gq gq1">B.tech IIT</p>
                    <p class="gie gl gl1">{{q.guide.guideinfo.level}}</p>
                    <p class="gie gr gr1">{{q.guide.guideinfo.rating}}</p>
                </div>
                <div class=" qai qa1">
                    <p class="q">{{q.ques}}</p>
                    <p class="a">{{q.ans}}</p>
                </div>
                {%endfor%}
            </div>
            {{ fd.name| json_script:'fd'}}
        <script src="{% static 'jsqueslst.js' %}">
        </script>
    </body>
</html>